name: Firebase 
 
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          sudo npm install -g firebase-tools
          firebase deploy --token ${{ secrets.TOKEN }} 